language: node_js
node_js:
    - "0.10"
before_script:
    - "npm install karma"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
    - "karma start --browsers=PhantomJS,Firefox --reporters=dots"
